#!/bin/sh
#
# Usage:
# % sudo apt-get install curl git zsh
# % curl -sk https://raw.githubusercontent.com/imotov/dotfiles/master/bootstrap | zsh

set -e
rm -rf ~/.oh-my-zsh
rm -rf ~/.dotfiles
git clone -q git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cd ~/.oh-my-zsh/plugins && git clone -q git://github.com/zsh-users/zsh-syntax-highlighting.git
git clone -q https://github.com/imotov/dotfiles.git ~/.dotfiles
. ~/.dotfiles/push

pushd ~/.dotfiles
# Set proper url for .dotfiles remote repository
git remote set-url origin git@github.com:imotov/dotfiles.git
popd

OS=$(uname)
if [ $OS = "Darwin" ]; then
  curl -L -o ~/Downloads/WindowHalfsAndThirds.spoon.zip https://github.com/Hammerspoon/Spoons/raw/master/Spoons/WindowHalfsAndThirds.spoon.zip
  mkdir -p ~/.hammerspoon/Spoons
  pushd ~/.hammerspoon/Spoons
  unzip ~/Downloads/WindowHalfsAndThirds.spoon.zip
  popd

  git clone https://github.com/nvm-sh/nvm.git ~/.nvm
  pushd ~/.nvm
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
  popd
fi


echo "Done."
