#!/bin/sh
#
# Usage:
# % curl -sk https://raw.githubusercontent.com/imotov/dotfiles/master/bootstrap | zsh

rm -rf ~/.oh-my-zsh
rm -rf ~/.dotfiles
git clone -q git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cd ~/.oh-my-zsh/plugins && git clone -q git://github.com/zsh-users/zsh-syntax-highlighting.git
git clone -q git://github.com/imotov/dotfiles.git ~/.dotfiles
. ~/.dotfiles/push

pushd ~/.dotfiles
# Set proper url for .dotfiles remote repository
git remote set-url origin git@github.com:imotov/dotfiles.git
echo "Done."