#!/usr/bin/env zsh

NAME=$(uname -n)

# zsh files
cp -f -p -v ~/.zshrc ./zshrc
cp -f -p -v ~/.tmux.conf ./tmux.conf
mkdir -p oh-my-zsh/custom
mkdir -p oh-my-zsh/themes
cp -f -p -v ~/.oh-my-zsh/custom/*.zsh oh-my-zsh/custom/
cp -f -p -v ~/.oh-my-zsh/themes/imotov.zsh-theme oh-my-zsh/themes/

# editor files
cp -f -p -v ~/.atom/*.cson ~/.atom/*.coffee ~/.atom/*.less ./atom 2>&1 | grep -v 'not copied'

# Mac OSX specific part
OS=$(uname)
if [ $OS = "Darwin" ]; then
    cp -f -p -v ~/.gitconfig  ./gitconfig.osx

    # other files
    cp -f -p -rv ~/.MacOSX/* ./MacOSX

    # copy idea.properties and idea.vmoptions files
    cp -f -p -v ~/Library/Application\ Support/JetBrains/IdeaIC2021.1/idea.vmoptions idea/

else
  cp -f -p -v ~/.gitconfig ./gitconfig
  # need to increase Java heap size on Linux
  if [[ $NAME == "grasshopper" ]]; then
    cp -f -p -v ~/.config/JetBrains/IntelliJIdea2021.1/idea64.vmoptions idea/
  else
    cp -f -p -v ~/.config/JetBrains/IdeaIC2021.1/idea64.vmoptions idea/
  fi
fi
