#!/usr/bin/env zsh

NAME=$(uname -n)
setopt +o nomatch &&
cp -f -p ~/.dotfiles/zshrc ~/.zshrc
rm -f ~/.oh-my-zsh/custom/??_*.zsh
cp -f -p ~/.dotfiles/oh-my-zsh/custom/*.zsh ~/.oh-my-zsh/custom/
cp -f -p ~/.dotfiles/oh-my-zsh/themes/imotov.zsh-theme ~/.oh-my-zsh/themes/

# Platform independent
cp -f -p ~/.dotfiles/tmux.conf ~/.tmux.conf

# Platform dependent
OS=$(uname)
if [ $OS = "Darwin" ]; then
  cp -f -p ~/.dotfiles/gitconfig.osx ~/.gitconfig

  mkdir -p ~/Library/Application\ Support/JetBrains/IdeaIC2021.1/
  cp -f -p ~/.dotfiles/idea/idea.vmoptions ~/Library/Application\ Support/JetBrains/IdeaIC2021.1/
else
  # Linux specific part
  cp -f -p ~/.dotfiles/gitconfig ~/.gitconfig

  mkdir -p ~/.config/JetBrains/IdeaIC2020.1/
  cp -f -p ~/.dotfiles/idea/idea64.vmoptions ~/.config/JetBrains/IdeaIC2020.1/
fi
